local_backend:
  url: http://localhost:9000

backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "puzzles"
    label: "Puzzles"
    format: "json"
    editor: { preview: false }
    files:
      - name: "puzzles"
        label: "Puzzles List"
        file: "assets/products.json"
        fields:
          - { name: items, label: Items, widget: list, collapsed: true, fields: [
              { name: title, widget: string, label: Title },
              { name: price, widget: number, value_type: float, min: 0, label: Price },
              { name: dimensions, widget: string, required: false, label: Dimensions/Notes },
              { name: image, widget: image, label: Image },
              { name: paypal, widget: string, required: false, label: Override PayPal URL },
              { name: cashapp, widget: string, required: false, label: Override Cash App URL }
            ] }
  - name: "art"
    label: "Art Exhibit"
    format: "json"
    editor: { preview: false }
    files:
      - name: "art"
        label: "Art List"
        file: "assets/art.json"
        fields:
          - { name: items, label: Items, widget: list, collapsed: true, fields: [
              { name: title, widget: string, label: Title },
              { name: price, widget: number, value_type: float, min: 0, required: false, label: Price },
              { name: dimensions, widget: string, required: false, label: Dimensions/Notes },
              { name: image, widget: image, label: Image }
            ] }
  - name: "crochet"
    label: "Crochet"
    format: "json"
    editor: { preview: false }
    files:
      - name: "crochet"
        label: "Crochet List"
        file: "assets/crochet.json"
        fields:
          - { name: items, label: Items, widget: list, collapsed: true, fields: [
              { name: title, widget: string, label: Title },
              { name: price, widget: number, value_type: float, min: 0, required: false, label: Price },
              { name: dimensions, widget: string, required: false, label: Dimensions/Notes },
              { name: image, widget: image, label: Image }
            ] }
