backend:
  name: git-gateway
  branch: main
# local_backend: true

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "assets/config.json"
        label: "Payments & Tips"
        name: "config"
        fields:
          - { label: "Site Name", name: "site_name", widget: "string" }
          - { label: "Version", name: "version", widget: "string" }
          - label: "Payments"
            name: "payments"
            widget: "object"
            fields:
              - label: "Dewayne (Tips)"
                name: "dewayne"
                widget: "object"
                fields:
                  - { label: "Cash App (Tip)", name: "tip_cashapp", widget: "string" }
                  - { label: "Venmo (Tip)", name: "tip_venmo", widget: "string" }
                  - { label: "PayPal.Me (Tip)", name: "tip_paypal", widget: "string" }
              - label: "Sean (Product Sales)"
                name: "sean"
                widget: "object"
                fields:
                  - { label: "PayPal default", name: "paypal_default", widget: "string" }
                  - { label: "Cash App default", name: "cashapp_default", widget: "string" }
          - label: "Tip Page"
            name: "tips"
            widget: "object"
            fields:
              - { label: "Suggested Amounts", name: "amounts", widget: "list", field: {label: "Amount", name: "amount", widget: "number", value_type: "int", min: 1} }
              - { label: "Cash App $Tag (fallback)", name: "cash_tag", widget: "string" }
              - { label: "PayPal.Me handle (fallback)", name: "paypal_me", widget: "string" }
              - { label: "Venmo @User (fallback)", name: "venmo_user", widget: "string" }
              - { label: "Note text", name: "note", widget: "string" }

  - name: "products"
    label: "Puzzles"
    editor: { preview: false }
    files:
      - file: "assets/products.json"
        label: "Puzzle Catalog"
        name: "products"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.title}} — ${{fields.price}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Price (USD)", name: "price", widget: "number", value_type: "float", min: 0 }
              - { label: "Dimensions", name: "dimensions", widget: "string" }
              - { label: "Image", name: "image", widget: "image", media_folder: "assets/img/products", public_folder: "/assets/img/products" }

  - name: "art"
    label: "Art Exhibit"
    files:
      - file: "assets/art.json"
        label: "Art Items"
        name: "art"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.title}} — ${{fields.price}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Price (USD)", name: "price", widget: "number", value_type: "float", min: 0 }
              - { label: "Dimensions/Medium", name: "dimensions", widget: "string" }
              - { label: "Image", name: "image", widget: "image", media_folder: "assets/img/art", public_folder: "/assets/img/art" }

  - name: "crochet"
    label: "Crochet"
    files:
      - file: "assets/crochet.json"
        label: "Crochet Items"
        name: "crochet"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.title}} — ${{fields.price}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Price (USD)", name: "price", widget: "number", value_type: "float", min: 0 }
              - { label: "Notes", name: "dimensions", widget: "string" }
              - { label: "Image", name: "image", widget: "image", media_folder: "assets/img/crochet", public_folder: "/assets/img/crochet" }

  - name: "tiktok"
    label: "TikTok"
    files:
      - file: "assets/tiktok.json"
        label: "TikTok Feed"
        name: "tiktok"
        fields:
          - { label: "Profile URL", name: "profile_url", widget: "string" }
          - label: "Posts"
            name: "items"
            widget: "list"
            field: { label: "Video URL", name: "url", widget: "string" }

  - name: "certs"
    label: "Certifications"
    files:
      - file: "assets/certs.json"
        label: "Badge List"
        name: "certs"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image", media_folder: "assets/img/certs", public_folder: "/assets/img/certs" }
              - { label: "Verification Link (optional)", name: "link", widget: "string", required: false }
