backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "puzzles"
    label: "Puzzles"
    files:
      - label: "Puzzles List"
        name: "puzzles_list"
        file: "assets/products.json"
        format: json
        fields:
          - {label: Items, name: items, widget: list, collapsed: false, fields: [
              {label: Title, name: title, widget: string},
              {label: Price (USD), name: price, widget: number, value_type: float, min: 0},
              {label: Dimensions, name: dimensions, widget: string, required: false},
              {label: Image, name: image, widget: image},
              {label: Owner, name: owner, widget: select, options: ["sean","dewayne"], default: "sean"},
              {label: Accepts, name: accepts, widget: list, default: ["paypal","cashapp","venmo"]}
            ]}

  - name: "art"
    label: "Art"
    files:
      - label: "Art List"
        name: "art_list"
        file: "assets/art.json"
        format: json
        fields:
          - {label: Items, name: items, widget: list, collapsed: false, fields: [
              {label: Title, name: title, widget: string},
              {label: Price (USD), name: price, widget: number, value_type: float, min: 0},
              {label: Frame / Size, name: frame, widget: string, required: false},
              {label: Notes, name: notes, widget: string, default: "Buyer pays shipping", required: false},
              {label: Image, name: image, widget: image},
              {label: Owner, name: owner, widget: select, options: ["dewayne","sean"], default: "dewayne"},
              {label: Accepts, name: accepts, widget: list, default: ["paypal","cashapp","venmo"]}
            ]}
