
backend:
  name: git-gateway
  branch: main
media_folder: "assets/img"
public_folder: "/assets/img"
editorial_workflow: false
collections:
  - name: "puzzles"
    label: "Puzzles"
    format: "json"
    editor: { preview: false }
    files:
      - name: "puzzles"
        label: "Puzzles List"
        file: "assets/products.json"
        fields:
          - { label: Items, name: items, widget: list, collapsed: true, fields: [
              { label: Title, name: title, widget: string },
              { label: Price (USD), name: price, widget: number, value_type: float, min: 0 },
              { label: Dimensions, name: dimensions, widget: string, required: false },
              { label: Image, name: image, widget: image },
              { label: Override PayPal URL, name: paypal, widget: string, required: false },
              { label: Override Cash App URL, name: cashapp, widget: string, required: false }
          ] }
  - name: "art"
    label: "Art Exhibit"
    format: "json"
    editor: { preview: false }
    files:
      - name: "art"
        label: "Art List"
        file: "assets/art.json"
        fields:
          - { label: Items, name: items, widget: list, collapsed: true, fields: [
              { label: Title, name: title, widget: string },
              { label: Price (USD), name: price, widget: number, value_type: float, min: 0, required: false },
              { label: Dimensions, name: dimensions, widget: string, required: false },
              { label: Image, name: image, widget: image }
          ] }
  - name: "crochet"
    label: "Crochet"
    format: "json"
    editor: { preview: false }
    files:
      - name: "crochet"
        label: "Crochet List"
        file: "assets/crochet.json"
        fields:
          - { label: Items, name: items, widget: list, collapsed: true, fields: [
              { label: Title, name: title, widget: string },
              { label: Price (USD), name: price, widget: number, value_type: float, min: 0, required: false },
              { label: Dimensions, name: dimensions, widget: string, required: false },
              { label: Image, name: image, widget: image }
          ] }
