
# Copyright (c) 2025 Dewayne Cox (Wonder Piece Studio). All rights reserved.
[build]
  publish = "."

# Restrict Admin Tools to logged-in Identity users with role "admin"
[[redirects]]
  from = "/admin/tools"
  to = "/admin/tools.html"
  status = 200
  force = true
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/admin/tools.html"
  to = "/admin/tools.html"
  status = 200
  force = true
  conditions = { Role = ["admin"] }
